=== consultant-1379/eric-oss-network-assurance-search/consumer-contract-tests/cnomJsonSchemas/dashboardModel.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://cnom.ericsson.com/schemas/dashboardModel.schema.json",
  "title": "Dashboard model",
  "description": "Contains a namespace and any number of dashboards, widgets and sources. Usually each dashboard model would contain one dashboard and all its widgets and sources.",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "$schema": {
      "description": "This can be used by editors to provide hints and verify that the JSON can be read correctly by CNOM. Currently only possible to use by CNOM developers.",
      "type": "string"
    },
    "namespace": {
      "description": "If present, specifies the namespace for everything in the dashboard model. This is a CNOM dashboard model specific namespace and not related to the Kubernetes namespace.",
      "type": "string",
      "pattern": "^[^:]+$"
    },
    "dashboards": {
      "description": "A list of dashboards.",
      "type": "array",
      "items": { "$ref": "dashboard.schema.json" },
      "default": []
    },
    "widgets": {
      "description": "A list of widgets. A widget is a single GUI element in a dashboard. The widget is laid out in a grid layout.",
      "type": "array",
      "items": { "$ref": "./widgets/widget.schema.json" },
      "default": []
    },
    "sources": {
      "description": "A list of sources. A source defines an API call, often to an external peer service, to fetch data. This data can then be displayed in a widget. The returned data is always an array of {label1: value1, label2: value2, ...}.",
      "type": "array",
      "items": { "$ref": "./sources/source.schema.json" },
      "default": []
    }
  }
}

=== consultant-1379/eric-oss-network-assurance-search/frontend/mocks/components/historical-metrics-dashboard/fullHistoricalDashboardModel.json
{
  "$schema": "../../../server/jsonSchemas/dashboardModel.schema.json",
  "namespace": "assurance",
  "dashboards": [
    {
      "_id": "dashboard_zolemr24",
      "title": "tac_548 (timelines)",
      "tiles": [
        {
          "xSize": 8,
          "ySize": 1,
          "widget": "timeline_b5k79y7"
        },
        {
          "xSize": 8,
          "ySize": 1,
          "widget": "timeline_2l3mle4r"
        },
        {
          "xSize": 8,
          "ySize": 1,
          "widget": "timeline_3bku43e"
        }
      ]
    },
    {
      "_id": "dashboard_8o0kf22",
      "title": "tac_548 (bar charts)",
      "tiles": [
        {
          "xSize": 8,
          "ySize": 1,
          "widget": "barChart_9lyw30tr"
        },
        {
          "xSize": 8,
          "ySize": 1,
          "widget": "barChart_kz22lhkg"
        },
        {
          "xSize": 8,
          "ySize": 1,
          "widget": "barChart_z4vyf81d"
        }
      ]
    },
    {
      "_id": "dashboard_1ubjikcn",
      "title": "tac_548 (donut)",
      "tiles": [
        {
          "xSize": 8,
          "ySize": 1,
          "widget": "donut_2qcvgf2"
        },
        {
          "xSize": 8,
          "ySize": 1,
          "widget": "donut_lykbx1m"
        },
        {
          "xSize": 8,
          "ySize": 1,
          "widget": "donut_cb9j6uc6"
        }
      ]
    },
    {
      "_id": "dashboard_hd7jet8s",
      "title": "tac_548 (kpi)",
      "tiles": [
        {
          "xSize": 8,
          "ySize": 1,
          "widget": "kpi_bu3hvwis"
        },
        {
          "xSize": 8,
          "ySize": 1,
          "widget": "kpi_2ojtpuqph"
        },
        {
          "xSize": 8,
          "ySize": 1,
          "widget": "kpi_9n1fh0md"
        }
      ]
    },
    {
      "_id": "dashboard_5ztb0w6h",
      "title": "tac_548 (gauge)",
      "tiles": [
        {
          "xSize": 8,
          "ySize": 1,
          "widget": "gauge_lnge8cn"
        },
        {
          "xSize": 8,
          "ySize": 1,
          "widget": "gauge_c1039sdk"
        },
        {
          "xSize": 8,
          "ySize": 1,
          "widget": "gauge_fjc23h46"
        }
      ]
    }
  ],
  "widgets": [
    {
      "_id": "timeline_b5k79y7",
      "widgetType": "timeline",
      "title": "Partial DRB Accessibility,GRANGOSR,5GSEPHOSR",
      "subtitle": "tac_548",
      "sources": [
        {
          "source": "pmStatsQueryService_vd_tac_PartialDRBAccessibility_prqrm66l"
        },
        {
          "source": "pmStatsQueryService_vd_tac_GRANGOSR_3yv9mu8h"
        },
        {
          "source": "pmStatsQueryService_vd_tac_5GSEPHOSR_nqa5ma2f"
        }
      ],
      "thresholds": [
        {
          "condition": "moreThan",
          "value": 352,
          "color": "red"
        },
        {
          "condition": "lessThan",
          "value": 350,
          "color": "green"
        }
      ],
      "rightPanelContent": {
        "features": ["settings", "valuesTable"],
        "openByDefault": "none"
      }
    },
    {
      "_id": "timeline_2l3mle4r",
      "widgetType": "timeline",
      "title": "DLLat_gNB-DU,DLDelay_gNBDU",
      "subtitle": "tac_548",
      "sources": [
        {
          "source": "pmStatsQueryService_vd_tac_DLLat_gNB-DU_j4k4zvgr"
        },
        {
          "source": "pmStatsQueryService_vd_tac_DLDelay_gNBDU_05xms0zb"
        }
      ],
      "thresholds": [
        {
          "condition": "moreThan",
          "value": 352,
          "color": "red"
        },
        {
          "condition": "lessThan",
          "value": 350,
          "color": "green"
        }
      ],
      "rightPanelContent": {
        "features": ["settings", "valuesTable"],
        "openByDefault": "none"
      }
    },
    {
      "_id": "timeline_3bku43e",
      "widgetType": "timeline",
      "title": "DLUeThroughput,UlUeThroughput",
      "subtitle": "tac_548",
      "sources": [
        {
          "source": "pmStatsQueryService_vd_tac_DLUeThroughput_cj7bcef"
        },
        {
          "source": "pmStatsQueryService_vd_tac_UlUeThroughput_jv7qcu5"
        }
      ],
      "thresholds": [
        {
          "condition": "moreThan",
          "value": 352,
          "color": "red"
        },
        {
          "condition": "lessThan",
          "value": 350,
          "color": "green"
        }
      ],
      "rightPanelContent": {
        "features": ["settings", "valuesTable"],
        "openByDefault": "none"
      }
    },
    {
      "_id": "barChart_9lyw30tr",
      "widgetType": "barChart",
      "title": "Partial DRB Accessibility,GRANGOSR,5GSEPHOSR",
      "subtitle": "tac_548",
      "sources": [
        {
          "source": "pmStatsQueryService_vd_tac_PartialDRBAccessibility_prqrm66l"
        },
        {
          "source": "pmStatsQueryService_vd_tac_GRANGOSR_3yv9mu8h"
        },
        {
          "source": "pmStatsQueryService_vd_tac_5GSEPHOSR_nqa5ma2f"
        }
      ],
      "thresholds": [
        {
          "condition": "moreThan",
          "value": 92,
          "color": "red"
        },
        {
          "condition": "lessThan",
          "value": 90,
          "color": "green"
        }
      ]
    },
    {
      "_id": "barChart_kz22lhkg",
      "widgetType": "barChart",
      "title": "DLLat_gNB-DU,DLDelay_gNBDU",
      "subtitle": "tac_548",
      "sources": [
        {
          "source": "pmStatsQueryService_vd_tac_DLLat_gNB-DU_j4k4zvgr"
        },
        {
          "source": "pmStatsQueryService_vd_tac_DLDelay_gNBDU_05xms0zb"
        }
      ],
      "thresholds": [
        {
          "condition": "moreThan",
          "value": 92,
          "color": "red"
        },
        {
          "condition": "lessThan",
          "value": 90,
          "color": "green"
        }
      ]
    },
    {
      "_id": "barChart_z4vyf81d",
      "widgetType": "barChart",
      "title": "DLUeThroughput,UlUeThroughput",
      "subtitle": "tac_548",
      "sources": [
        {
          "source": "pmStatsQueryService_vd_tac_DLUeThroughput_cj7bcef"
        },
        {
          "source": "pmStatsQueryService_vd_tac_UlUeThroughput_jv7qcu5"
        }
      ],
      "thresholds": [
        {
          "condition": "moreThan",
          "value": 92,
          "color": "red"
        },
        {
          "condition": "lessThan",
          "value": 90,
          "color": "green"
        }
      ]
    },
    {
      "_id": "kpi_bu3hvwis",
      "widgetType": "kpi",
      "title": "Partial DRB Accessibility,GRANGOSR,5GSEPHOSR",
      "subtitle": "tac_548",
      "sources": [
        {
          "source": "pmStatsQueryService_vd_tac_PartialDRBAccessibility_prqrm66l",
          "heading": "Partial DRB Accessibility",
          "kpiType": "progressBar",
          "extraData": {
            "maxValue": 100
          }
        },
        {
          "source": "pmStatsQueryService_vd_tac_GRANGOSR_3yv9mu8h",
          "heading": "GRANGOSR",
          "kpiType": "progressBar",
          "extraData": {
            "maxValue": 100
          }
        },
        {
          "source": "pmStatsQueryService_vd_tac_5GSEPHOSR_nqa5ma2f",
          "heading": "5GSEPHOSR",
          "kpiType": "progressBar",
          "extraData": {
            "maxValue": 100
          }
        }
      ],
      "showTimestamp": true
    },
    {
      "_id": "kpi_2ojtpuqph",
      "widgetType": "kpi",
      "title": "DLLat_gNB-DU,DLDelay_gNBDU",
      "subtitle": "tac_548",
      "sources": [
        {
          "source": "pmStatsQueryService_vd_tac_DLLat_gNB-DU_j4k4zvgr",
          "heading": "DLLat_gNB-DU",
          "kpiType": "progressBar",
          "extraData": {
            "maxValue": 100
          }
        },
        {
          "source": "pmStatsQueryService_vd_tac_DLDelay_gNBDU_05xms0zb",
          "heading": "DLDelay_gNBDU",
          "kpiType": "progressBar",
          "extraData": {
            "maxValue": 100
          }
        }
      ],
      "showTimestamp": true
    },
    {
      "_id": "kpi_9n1fh0md",
      "widgetType": "kpi",
      "title": "DLUeThroughput,UlUeThroughput",
      "subtitle": "tac_548",
      "sources": [
        {
          "source": "pmStatsQueryService_vd_tac_DLUeThroughput_cj7bcef",
          "heading": "DLUeThroughput",
          "kpiType": "progressBar",
          "extraData": {
            "maxValue": 100
          }
        },
        {
          "source": "pmStatsQueryService_vd_tac_UlUeThroughput_jv7qcu5",
          "heading": "UlUeThroughput",
          "kpiType": "progressBar",
          "extraData": {
            "maxValue": 100
          }
        }
      ],
      "showTimestamp": true
    },
    {
      "_id": "gauge_lnge8cn",
      "widgetType": "gauge",
      "title": "Partial DRB Accessibility,GRANGOSR,5GSEPHOSR",
      "subtitle": "tac_548",
      "sources": [
        {
          "source": "pmStatsQueryService_vd_tac_PartialDRBAccessibility_prqrm66l"
        },
        {
          "source": "pmStatsQueryService_vd_tac_GRANGOSR_3yv9mu8h"
        },
        {
          "source": "pmStatsQueryService_vd_tac_5GSEPHOSR_nqa5ma2f"
        }
      ],
      "size": "medium",
      "dataKey": "Cavendish",
      "min": 0,
      "max": 100,
      "limits": [
        {
          "from": 1,
          "to": 10,
          "label": "Low",
          "color": "red"
        },
        {
          "from": 90,
          "to": 100,
          "label": "High",
          "color": "yellow"
        },
        {
          "from": 10,
          "to": 90,
          "label": "Normal",
          "color": "transparent"
        }
      ]
    },
    {
      "_id": "gauge_c1039sdk",
      "widgetType": "gauge",
      "title": "DLLat_gNB-DU,DLDelay_gNBDU",
      "subtitle": "tac_548",
      "sources": [
        {
          "source": "pmStatsQueryService_vd_tac_DLLat_gNB-DU_j4k4zvgr"
        },
        {
          "source": "pmStatsQueryService_vd_tac_DLDelay_gNBDU_05xms0zb"
        }
      ],
      "size": "medium",
