=== consultant-1379/eric-oss-network-assurance-search/backend/utils/opensearchJsonSchemas/responseModel.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://nas.ericsson.com/schemas/opensearchResponseModel.schema.json",
  "title": "Opensearch Response Model Schema",
  "description": "The schema for the response object coming from Opensearch after a successful request has been made.",
  "type": "object",
  "properties": {
    "took": {
      "description": "Time it took to complete query.",
      "type": "integer"
    },
    "timed_out": {
      "description": "Indicates whether the response timed out or not.",
      "type": "boolean"
    },
    "_shards": {
      "type": "object",
      "properties": {
        "total": {
          "type": "integer"
        },
        "successful": {
          "type": "integer"
        },
        "skipped": {
          "type": "integer"
        },
        "failed": {
          "type": "integer"
        }
      }
    },
    "hits": {
      "description": "An object that contains the query results and it's metadata.",
      "$ref": "https://nas.ericsson.com/schemas/opensearchHitsModel.schema.json"
    }
  },
  "required": ["hits"]
}

=== consultant-1379/eric-oss-network-assurance-search/backend/test/mocks/opensearch/search/metrics/filtering/nameFilterTestQuery1Response.json
{
  "took": 4,
  "timed_out": false,
  "_shards": {
    "total": 1,
    "successful": 1,
    "skipped": 0,
    "failed": 0
  },
  "hits": {
    "total": {
      "value": 7,
      "relation": "eq"
    },
    "max_score": null,
    "hits": [
      {
        "_index": "soa",
        "_id": "AMFMeanRegNbr@NF:AMF_BC::SNSSAI:1:1::",
        "_score": null,
        "_source": {
          "full_context": "NF_SNSSAI",
          "context": ["SNSSAI", "NF"],
          "c_SNSSAI": "1:1",
          "c_NF": "AMF_BC",
          "vi_NF_SNSSAI_AMFMeanRegNbr": 10
        },
        "sort": [10]
      },
      {
        "_index": "soa",
        "_id": "AMFMeanRegNbr@NF:AMF_BC::SNSSAI:1:2::",
        "_score": null,
        "_source": {
          "full_context": "NF_SNSSAI",
          "context": ["SNSSAI", "NF"],
          "c_SNSSAI": "1:2",
          "c_NF": "AMF_BC",
          "vi_NF_SNSSAI_AMFMeanRegNbr": 20
        },
        "sort": [20]
      },
      {
        "_index": "soa",
        "_id": "AMFMeanRegNbr@NF:AMF_BC::SNSSAI:2:1::",
        "_score": null,
        "_source": {
          "full_context": "NF_SNSSAI",
          "context": ["SNSSAI", "NF"],
          "c_SNSSAI": "2:1",
          "c_NF": "AMF_BC",
          "vi_NF_SNSSAI_AMFMeanRegNbr": 30
        },
        "sort": [30]
      },
      {
        "_index": "soa",
        "_id": "AMFMeanRegNbr@NF:AMF_ON1::SNSSAI:2:1::",
        "_score": null,
        "_source": {
          "full_context": "NF_SNSSAI",
          "context": ["SNSSAI", "NF"],
          "c_SNSSAI": "2:1",
          "c_NF": "AMF_ON1",
          "vi_NF_SNSSAI_AMFMeanRegNbr": 40
        },
        "sort": [40]
      },
      {
        "_index": "soa",
        "_id": "AMFMeanRegNbr@NF:AMF_ON1::SNSSAI:2:2::",
        "_score": null,
        "_source": {
          "full_context": "NF_SNSSAI",
          "context": ["SNSSAI", "NF"],
          "c_SNSSAI": "2:2",
          "c_NF": "AMF_ON1",
          "vi_NF_SNSSAI_AMFMeanRegNbr": 50
        },
        "sort": [50]
      },
      {
        "_index": "soa",
        "_id": "AMFMeanRegNbr@NF:AMF_ON2::SNSSAI:2:1::",
        "_score": null,
        "_source": {
          "full_context": "NF_SNSSAI",
          "context": ["SNSSAI", "NF"],
          "c_SNSSAI": "2:1",
          "c_NF": "AMF_ON2",
          "vi_NF_SNSSAI_AMFMeanRegNbr": 60
        },
        "sort": [60]
      },
      {
        "_index": "soa",
        "_id": "AMFMeanRegNbr@NF:AMF_ON2::SNSSAI:2:2::",
        "_score": null,
        "_source": {
          "full_context": "NF_SNSSAI",
          "context": ["SNSSAI", "NF"],
          "c_SNSSAI": "2:2",
          "c_NF": "AMF_ON2",
          "vi_NF_SNSSAI_AMFMeanRegNbr": 70
        },
        "sort": [70]
      }
    ]
  }
}

=== consultant-1379/eric-oss-network-assurance-search/backend/test/mocks/opensearch/search/metrics/filtering/nameFilterTestQuery2Response.json
{
  "took": 6,
  "timed_out": false,
  "_shards": {
    "total": 1,
    "successful": 1,
    "skipped": 0,
    "failed": 0
  },
  "hits": {
    "total": {
      "value": 15,
      "relation": "eq"
    },
    "max_score": 4.0893116,
    "hits": [
      {
        "_index": "soa",
        "_id": "AMFMeanRegNbr@NF:AMF_ON1::SNSSAI:2:1::",
        "_score": 4.0893116,
        "_source": {
          "full_context": "NF_SNSSAI",
          "context": ["SNSSAI", "NF"],
          "c_SNSSAI": "2:1",
          "c_NF": "AMF_ON1",
          "vi_NF_SNSSAI_AMFMeanRegNbr": 40
        }
      },
      {
        "_index": "soa",
        "_id": "AMFMeanRegNbr3@NF:AMF_ON1::SNSSAI:2:1::",
        "_score": 4.0893116,
        "_source": {
          "full_context": "NF_SNSSAI",
          "context": ["SNSSAI", "NF"],
          "c_SNSSAI": "2:1",
          "c_NF": "AMF_ON1",
          "vi_NF_SNSSAI_AMFMeanRegNbr3": 40
        }
      },
      {
        "_index": "soa",
        "_id": "AMFMeanRegNbr@NF:AMF_BC::SNSSAI:1:1::",
        "_score": 3.9819288,
        "_source": {
          "full_context": "NF_SNSSAI",
          "context": ["SNSSAI", "NF"],
          "c_SNSSAI": "1:1",
          "c_NF": "AMF_BC",
          "vi_NF_SNSSAI_AMFMeanRegNbr": 10
        }
      },
      {
        "_index": "soa",
        "_id": "AMFMeanRegNbr@NF:AMF_BC::SNSSAI:1:2::",
        "_score": 3.9819288,
        "_source": {
          "full_context": "NF_SNSSAI",
          "context": ["SNSSAI", "NF"],
          "c_SNSSAI": "1:2",
          "c_NF": "AMF_BC",
          "vi_NF_SNSSAI_AMFMeanRegNbr": 20
        }
      },
      {
        "_index": "soa",
        "_id": "AMFMeanRegNbr2@NF:AMF_BC::SNSSAI:1:1::",
        "_score": 3.9819288,
        "_source": {
          "full_context": "NF_SNSSAI",
          "context": ["SNSSAI", "NF"],
          "c_SNSSAI": "1:1",
          "c_NF": "AMF_BC",
          "vi_NF_SNSSAI_AMFMeanRegNbr2": 10
        }
      },
      {
        "_index": "soa",
        "_id": "AMFMeanRegNbr2@NF:AMF_BC::SNSSAI:1:2::",
        "_score": 3.9819288,
        "_source": {
          "full_context": "NF_SNSSAI",
          "context": ["SNSSAI", "NF"],
          "c_SNSSAI": "1:2",
          "c_NF": "AMF_BC",
          "vi_NF_SNSSAI_AMFMeanRegNbr2": 20
        }
      },
      {
        "_index": "soa",
        "_id": "AMFMeanRegNbr3@NF:AMF_BC::SNSSAI:1:1::",
        "_score": 3.9819288,
        "_source": {
          "full_context": "NF_SNSSAI",
          "context": ["SNSSAI", "NF"],
          "c_SNSSAI": "1:1",
          "c_NF": "AMF_BC",
          "vi_NF_SNSSAI_AMFMeanRegNbr3": 10
        }
      },
      {
        "_index": "soa",
        "_id": "AMFMeanRegNbr3@NF:AMF_BC::SNSSAI:1:2::",
        "_score": 3.9819288,
        "_source": {
          "full_context": "NF_SNSSAI",
          "context": ["SNSSAI", "NF"],
          "c_SNSSAI": "1:2",
          "c_NF": "AMF_BC",
          "vi_NF_SNSSAI_AMFMeanRegNbr3": 20
        }
      },
      {
        "_index": "soa",
        "_id": "AMFMeanRegNbr@NF:AMF_ON2::SNSSAI:2:1::",
        "_score": 3.9462109,
        "_source": {
          "full_context": "NF_SNSSAI",
          "context": ["SNSSAI", "NF"],
          "c_SNSSAI": "2:1",
          "c_NF": "AMF_ON2",
          "vi_NF_SNSSAI_AMFMeanRegNbr": 60
        }
      },
      {
        "_index": "soa",
        "_id": "AMFMeanRegNbr2@NF:AMF_ON2::SNSSAI:2:1::",
        "_score": 3.9462109,
        "_source": {
          "full_context": "NF_SNSSAI",
          "context": ["SNSSAI", "NF"],
          "c_SNSSAI": "2:1",
          "c_NF": "AMF_ON2",
          "vi_NF_SNSSAI_AMFMeanRegNbr2": 60
        }
      }
    ]
  }
}

=== consultant-1379/eric-oss-network-assurance-search/backend/test/mocks/opensearch/search/contexts/contextTypeId/query1Response.json
{
  "took": 4,
  "timed_out": false,
  "_shards": {
    "total": 5,
    "successful": 5,
    "skipped": 0,
    "failed": 0
  },
  "hits": {
    "total": {
      "value": 6,
      "relation": "eq"
    },
    "max_score": 3.6100698,
    "hits": [
      {
        "_index": "soa",
        "_type": "_doc",
        "_id": "AMFMeanRegNbr2__SNSSAI_1:1__Site_BC",
        "_score": 3.6100698,
        "_source": {
          "c_Site": "BC",
          "c_SNSSAI": "1:1",
          "full_context": "SNSSAI_Site",
          "context": ["SNSSAI", "Site"],
          "xc_eyJTaXRlIjp7Im5hbWUiOiJTaXRlIiwibmFtZVR5cGUiOiJzdHJhaWdodCJ9LCJTTlNTQUkiOnsibmFtZSI6ImdlbmVyaWMiLCJuYW1lVHlwZSI6ImNvbG9uU2VwYXJhdGVkIn19": true,
          "value_context": "SNSSAI_Site_AMFMeanRegNbr2",
          "value_name": "AMFMeanRegNbr2",
          "vi_SNSSAI_Site_AMFMeanRegNbr2": 0,
          "xv_SNSSAI_Site_AMFMeanRegNbr2_eyIiOnsibmFtZSI6IkFNRk1lYW5SZWdOYnIyIiwidHlwZSI6ImludGVnZXIifX0A": true,
          "doc_id": "AMFMeanRegNbr2__SNSSAI_1:1__Site_BC",
          "offset": "27",
          "vintage": "DB327BFF1106DDB6CCB208C666A6919B",
          "csac_table": "kpi_csac_simple_snssai_mofdn_15",
          "csac_column": "csac_0fcf6508_67cc_4969_a1f2_566c106e38b0",
          "ft_begin_timestamp": 1676241825,
          "ft_end_timestamp": 1676242825
        }
      },
      {
        "_index": "soa",
        "_type": "_doc",
        "_id": "AMFMeanRegNbr__SNSSAI_1:2__Site_BC",
        "_score": 3.6100698,
        "_source": {
          "c_Site": "BC",
          "c_SNSSAI": "1:2",
          "full_context": "SNSSAI_Site",
          "context": ["SNSSAI", "Site"],
          "xc_eyJTaXRlIjp7Im5hbWUiOiJTaXRlIiwibmFtZVR5cGUiOiJzdHJhaWdodCJ9LCJTTlNTQUkiOnsibmFtZSI6ImdlbmVyaWMiLCJuYW1lVHlwZSI6ImNvbG9uU2VwYXJhdGVkIn19": true,
          "value_context": "SNSSAI_Site_AMFMeanRegNbr",
          "value_name": "AMFMeanRegNbr",
          "vi_SNSSAI_Site_AMFMeanRegNbr": 0,
          "xv_SNSSAI_Site_AMFMeanRegNbr_eyIiOnsibmFtZSI6IkFNRk1lYW5SZWdOYnIiLCJ0eXBlIjoiaW50ZWdlciJ9fQAA": true,
          "doc_id": "AMFMeanRegNbr__SNSSAI_1:2__Site_BC",
          "offset": "28",
          "vintage": "DB327BFF1106DDB6CCB208C666A6919B",
          "csac_table": "kpi_csac_simple_snssai_mofdn_15",
          "csac_column": "csac_0fcf6508_67cc_4969_a1f2_566c106e38b0",
          "ft_begin_timestamp": 1676241825,
          "ft_end_timestamp": 1676242825
        }
      },
      {
        "_index": "soa",
        "_type": "_doc",
        "_id": "AMFMeanRegNbr3__SNSSAI_1:1__Site_BC",
        "_score": 3.4849067,
        "_source": {
          "c_Site": "BC",
          "c_SNSSAI": "1:1",
          "full_context": "SNSSAI_Site",
          "context": ["SNSSAI", "Site"],
          "xc_eyJTaXRlIjp7Im5hbWUiOiJTaXRlIiwibmFtZVR5cGUiOiJzdHJhaWdodCJ9LCJTTlNTQUkiOnsibmFtZSI6ImdlbmVyaWMiLCJuYW1lVHlwZSI6ImNvbG9uU2VwYXJhdGVkIn19": true,
          "value_context": "SNSSAI_Site_AMFMeanRegNbr3",
          "value_name": "AMFMeanRegNbr3",
          "vi_SNSSAI_Site_AMFMeanRegNbr3": 10,
          "xv_SNSSAI_Site_AMFMeanRegNbr3_eyIiOnsibmFtZSI6IkFNRk1lYW5SZWdOYnIzIiwidHlwZSI6ImludGVnZXIifX0A": true,
          "doc_id": "AMFMeanRegNbr3__SNSSAI_1:1__Site_BC",
          "offset": "27",
          "vintage": "DB327BFF1106DDB6CCB208C666A6919B",
          "csac_table": "kpi_csac_simple_snssai_mofdn_15",
          "csac_column": "csac_0fcf6508_67cc_4969_a1f2_566c106e38b0",
          "ft_begin_timestamp": 1676241825,
          "ft_end_timestamp": 1676242825
        }
      },
      {
        "_index": "soa",
        "_type": "_doc",
        "_id": "AMFMeanRegNbr3__SNSSAI_1:2__Site_BC",
        "_score": 2.7560413,
        "_source": {
          "c_Site": "BC",
          "c_SNSSAI": "1:2",
          "full_context": "SNSSAI_Site",
          "context": ["SNSSAI", "Site"],
          "xc_eyJTaXRlIjp7Im5hbWUiOiJTaXRlIiwibmFtZVR5cGUiOiJzdHJhaWdodCJ9LCJTTlNTQUkiOnsibmFtZSI6ImdlbmVyaWMiLCJuYW1lVHlwZSI6ImNvbG9uU2VwYXJhdGVkIn19": true,
          "value_context": "SNSSAI_Site_AMFMeanRegNbr3",
          "value_name": "AMFMeanRegNbr3",
          "vi_SNSSAI_Site_AMFMeanRegNbr3": 20,
          "xv_SNSSAI_Site_AMFMeanRegNbr3_eyIiOnsibmFtZSI6IkFNRk1lYW5SZWdOYnIzIiwidHlwZSI6ImludGVnZXIifX0A": true,
          "doc_id": "AMFMeanRegNbr3__SNSSAI_1:2__Site_BC",
          "offset": "28",
          "vintage": "DB327BFF1106DDB6CCB208C666A6919B",
          "csac_table": "kpi_csac_simple_snssai_mofdn_15",
          "csac_column": "csac_0fcf6508_67cc_4969_a1f2_566c106e38b0",
          "ft_begin_timestamp": 1676241825,
          "ft_end_timestamp": 1676242825
        }
      },
      {
        "_index": "soa",
        "_type": "_doc",
        "_id": "AMFMeanRegNbr__SNSSAI_1:1__Site_BC",
        "_score": 2.598856,
        "_source": {
          "c_Site": "BC",
          "c_SNSSAI": "1:1",
          "full_context": "SNSSAI_Site",
          "context": ["SNSSAI", "Site"],
          "xc_eyJTaXRlIjp7Im5hbWUiOiJTaXRlIiwibmFtZVR5cGUiOiJzdHJhaWdodCJ9LCJTTlNTQUkiOnsibmFtZSI6ImdlbmVyaWMiLCJuYW1lVHlwZSI6ImNvbG9uU2VwYXJhdGVkIn19": true,
          "value_context": "SNSSAI_Site_AMFMeanRegNbr",
          "value_name": "AMFMeanRegNbr",
          "vi_SNSSAI_Site_AMFMeanRegNbr": 0,
          "xv_SNSSAI_Site_AMFMeanRegNbr_eyIiOnsibmFtZSI6IkFNRk1lYW5SZWdOYnIiLCJ0eXBlIjoiaW50ZWdlciJ9fQAA": true,
          "doc_id": "AMFMeanRegNbr__SNSSAI_1:1__Site_BC",
          "offset": "27",
          "vintage": "DB327BFF1106DDB6CCB208C666A6919B",
          "csac_table": "kpi_csac_simple_snssai_mofdn_15",
          "csac_column": "csac_0fcf6508_67cc_4969_a1f2_566c106e38b0",
          "ft_begin_timestamp": 1676241825,
          "ft_end_timestamp": 1676242825
        }
      },
      {
        "_index": "soa",
        "_type": "_doc",
        "_id": "AMFMeanRegNbr2__SNSSAI_1:2__Site_BC",
        "_score": 2.319603,
        "_source": {
          "c_Site": "BC",
          "c_SNSSAI": "1:2",
          "full_context": "SNSSAI_Site",
          "context": ["SNSSAI", "Site"],
          "xc_eyJTaXRlIjp7Im5hbWUiOiJTaXRlIiwibmFtZVR5cGUiOiJzdHJhaWdodCJ9LCJTTlNTQUkiOnsibmFtZSI6ImdlbmVyaWMiLCJuYW1lVHlwZSI6ImNvbG9uU2VwYXJhdGVkIn19": true,
          "value_context": "SNSSAI_Site_AMFMeanRegNbr2",
          "value_name": "AMFMeanRegNbr2",
          "vi_SNSSAI_Site_AMFMeanRegNbr2": 0,
          "xv_SNSSAI_Site_AMFMeanRegNbr2_eyIiOnsibmFtZSI6IkFNRk1lYW5SZWdOYnIyIiwidHlwZSI6ImludGVnZXIifX0A": true,
          "doc_id": "AMFMeanRegNbr2__SNSSAI_1:2__Site_BC",
          "offset": "28",
          "vintage": "DB327BFF1106DDB6CCB208C666A6919B",
          "csac_table": "kpi_csac_simple_snssai_mofdn_15",
          "csac_column": "csac_0fcf6508_67cc_4969_a1f2_566c106e38b0",
          "ft_begin_timestamp": 1676241825,
          "ft_end_timestamp": 1676242825
        }
      }
    ]
  }
}
